from django.http import HttpResponse
from portalApp.models import topic,subTopic, course, lecture,jobLocationAvailable,qualificationAvailable, extendedUser
from django.contrib.auth.models import User
from django.db.models import Q

def uploadData(request):

    course.objects.create(courseId=101,courseName='Master in Full Stack Web Development with AWS', courseTopicIds=[1001,1002,1003,1004,1005, 1006, 1007, 1008, 1009])

    topic.objects.create(topicId=1001, topicName='Foundation with SQL', selfLearningTopic=False)
    topic.objects.create(topicName='Web Designing Essential', selfLearningTopic=False)
    topic.objects.create(topicName='Python Essential', selfLearningTopic=False)
    topic.objects.create(topicName='Profile Building', selfLearningTopic=False)
    topic.objects.create(topicName='AWS Cloud Practitioner', selfLearningTopic=False)
    topic.objects.create(topicName='Java Essential', selfLearningTopic=True)
    topic.objects.create(topicName='Web Designing Professional', selfLearningTopic=True)
    topic.objects.create(topicName='Angular', selfLearningTopic=True)
    topic.objects.create(topicName='SQL Professional', selfLearningTopic=True)


    topicID=topic.objects.get(topicId=1001)
    subTopic.objects.create(subTopicId=10001, subTopicName='Computer Program', topicId=topicID)
    subTopic.objects.create(subTopicName='Conditional Statement', topicId=topicID)
    subTopic.objects.create(subTopicName='Iterative Statement', topicId=topicID)
    subTopic.objects.create(subTopicName='Introduction To SQL', topicId=topicID)
    subTopic.objects.create(subTopicName='DDL', topicId=topicID)
    subTopic.objects.create(subTopicName='DML', topicId=topicID)
    subTopic.objects.create(subTopicName='DQL', topicId=topicID)
    subTopic.objects.create(subTopicName='Built In SQL', topicId=topicID)
    subTopic.objects.create(subTopicName='Joins And Sub Query', topicId=topicID)

    topicID=topic.objects.get(topicId=1002)
    subTopic.objects.create(subTopicName='Introduction To HTML And Basic Tags', topicId=topicID)
    subTopic.objects.create(subTopicName='Tables And Form Elements', topicId=topicID)
    subTopic.objects.create(subTopicName='Introduction To CSS', topicId=topicID)
    subTopic.objects.create(subTopicName='CSS Properties', topicId=topicID)
    subTopic.objects.create(subTopicName='Introduction To Javascript', topicId=topicID)
    subTopic.objects.create(subTopicName='Consuming API', topicId=topicID)

    topicID=topic.objects.get(topicId=1003)
    subTopic.objects.create(subTopicName="Introduction To Python", topicId=topicID)
    subTopic.objects.create(subTopicName="Operators In Python", topicId=topicID)
    subTopic.objects.create(subTopicName="Conditional Statement", topicId=topicID)
    subTopic.objects.create(subTopicName="Loops In Python", topicId=topicID)
    subTopic.objects.create(subTopicName="More On Data Types", topicId=topicID)
    subTopic.objects.create(subTopicName="Guess The Word Project", topicId=topicID)
    subTopic.objects.create(subTopicName="Function And Modules", topicId=topicID)
    subTopic.objects.create(subTopicName="Project On Alice In The Wornderland", topicId=topicID)
    subTopic.objects.create(subTopicName="OOPS In Python", topicId=topicID)
    subTopic.objects.create(subTopicName="Introduction To Django", topicId=topicID)
    subTopic.objects.create(subTopicName="Pet Store With Django", topicId=topicID)
    subTopic.objects.create(subTopicName="Django Project Structure", topicId=topicID)
    subTopic.objects.create(subTopicName="Products Component", topicId=topicID)
    subTopic.objects.create(subTopicName="Templates", topicId=topicID)
    subTopic.objects.create(subTopicName="Bootstrap", topicId=topicID)
    subTopic.objects.create(subTopicName="Search Component", topicId=topicID)
    subTopic.objects.create(subTopicName="Cart Component", topicId=topicID)
    subTopic.objects.create(subTopicName="Checkout Process", topicId=topicID)
    subTopic.objects.create(subTopicName="User Account Registration, Login Using Auth Application.", topicId=topicID)
    subTopic.objects.create(subTopicName="Deploying Our Pet Store Application To Server", topicId=topicID)
    subTopic.objects.create(subTopicName="Software Testing", topicId=topicID)

    topicID=topic.objects.get(topicId=1004)
    subTopic.objects.create(subTopicName="Resume Transformation",topicId=topicID)
    subTopic.objects.create(subTopicName="Digital Success",topicId=topicID)
    subTopic.objects.create(subTopicName="Winning The Interview",topicId=topicID)
    subTopic.objects.create(subTopicName="The Job Hunt",topicId=topicID)

    topicID=topic.objects.get(topicId=1005)
    subTopic.objects.create(subTopicName="Introduction To Cloud Computing", topicId=topicID)
    subTopic.objects.create(subTopicName="Compute Services", topicId=topicID)
    subTopic.objects.create(subTopicName="AWS Storage Services", topicId=topicID)
    subTopic.objects.create(subTopicName="Elastic Load Balancing (ELB)", topicId=topicID)
    subTopic.objects.create(subTopicName="Databases", topicId=topicID)
    subTopic.objects.create(subTopicName="AWS Global Infrastructure", topicId=topicID)
    subTopic.objects.create(subTopicName="Infrastructure Management", topicId=topicID)
    subTopic.objects.create(subTopicName="Application Integration Services", topicId=topicID)
    subTopic.objects.create(subTopicName="Cloud Monitoring", topicId=topicID)
    subTopic.objects.create(subTopicName="VPC & Networking", topicId=topicID)
    subTopic.objects.create(subTopicName="Security", topicId=topicID)
    subTopic.objects.create(subTopicName="Other Services Overview", topicId=topicID)

    topicID=topic.objects.get(topicId=1006)
    subTopic.objects.create(subTopicName="Introduction To Java", topicId=topicID)
    subTopic.objects.create(subTopicName="Variables, Data Types", topicId=topicID)
    subTopic.objects.create(subTopicName="Operators & Tokens", topicId=topicID)
    subTopic.objects.create(subTopicName="Control Structures & Looping", topicId=topicID)
    subTopic.objects.create(subTopicName="Arrays", topicId=topicID)
    subTopic.objects.create(subTopicName="Guess The Word Project", topicId=topicID)
    subTopic.objects.create(subTopicName="OOPS - Classes & Objects In-Depth", topicId=topicID)
    subTopic.objects.create(subTopicName="OOPS - Abstraction, Inheritance & Polymorphism", topicId=topicID)
    subTopic.objects.create(subTopicName="Strings", topicId=topicID)
    subTopic.objects.create(subTopicName="Exception Handling", topicId=topicID)
    subTopic.objects.create(subTopicName="File Handling & IO", topicId=topicID)
    subTopic.objects.create(subTopicName="Collection Framework & Lambda Expressions", topicId=topicID)
    subTopic.objects.create(subTopicName="Project On Alice In The Wonderland", topicId=topicID)
    subTopic.objects.create(subTopicName="Multi-Threading", topicId=topicID)
    subTopic.objects.create(subTopicName="Java New Features", topicId=topicID)
    subTopic.objects.create(subTopicName="Introduction To Spring Core", topicId=topicID)
    subTopic.objects.create(subTopicName="Spring MVC & Spring Boot", topicId=topicID)
    subTopic.objects.create(subTopicName="Spring With Project - Pet Store", topicId=topicID)
    subTopic.objects.create(subTopicName="Creating & Running Spring Application", topicId=topicID)
    subTopic.objects.create(subTopicName="Creating REST APIs", topicId=topicID)
    subTopic.objects.create(subTopicName="Validating The Request", topicId=topicID)
    subTopic.objects.create(subTopicName="Database Integration & JPA Repository", topicId=topicID)
    subTopic.objects.create(subTopicName="Using Data REST, Pagination & Sorting", topicId=topicID)
    subTopic.objects.create(subTopicName="Relationships & Projections", topicId=topicID)
    subTopic.objects.create(subTopicName="Security", topicId=topicID)
    subTopic.objects.create(subTopicName="Security - Registration & Login Flow", topicId=topicID)
    subTopic.objects.create(subTopicName="File Upload & Download", topicId=topicID)
    subTopic.objects.create(subTopicName="Create Frontend To Consume APIs", topicId=topicID)
    subTopic.objects.create(subTopicName="Unit Testing In Pet Store Project", topicId=topicID)
    subTopic.objects.create(subTopicName="Deploying Our Pet Store Application To Server Using CI/CD", topicId=topicID)

    topicID=topic.objects.get(topicId=1007)
    subTopic.objects.create(subTopicName="HTML 5 Elements", topicId=topicID)
    subTopic.objects.create(subTopicName="More On Properties", topicId=topicID)
    subTopic.objects.create(subTopicName="CSS3 Properties", topicId=topicID)
    subTopic.objects.create(subTopicName="Responsive Utilities", topicId=topicID)
    subTopic.objects.create(subTopicName="Introduction To Javascript", topicId=topicID)
    subTopic.objects.create(subTopicName="Variables,Datatypes And Operators", topicId=topicID)
    subTopic.objects.create(subTopicName="Conditional And Control Statements", topicId=topicID)
    subTopic.objects.create(subTopicName="Javascript Function", topicId=topicID)
    subTopic.objects.create(subTopicName="Javascript Objects", topicId=topicID)
    subTopic.objects.create(subTopicName="Document Object Model", topicId=topicID)
    subTopic.objects.create(subTopicName="Bootstrap", topicId=topicID)

    topicID=topic.objects.get(topicId=1008)
    subTopic.objects.create(subTopicName="Introduction To Angular", topicId=topicID)
    subTopic.objects.create(subTopicName="Angular Components", topicId=topicID)
    subTopic.objects.create(subTopicName="Data Binding", topicId=topicID)
    subTopic.objects.create(subTopicName="Pipes & Strong Typing",topicId=topicID)
    subTopic.objects.create(subTopicName="Directives", topicId=topicID)
    subTopic.objects.create(subTopicName="Component Communication", topicId=topicID)
    subTopic.objects.create(subTopicName="Using Services, Dependency Injection", topicId=topicID)
    subTopic.objects.create(subTopicName="RxJS & Calling API",topicId=topicID)
    subTopic.objects.create(subTopicName="Routing And Navigation", topicId=topicID)
    subTopic.objects.create(subTopicName="Angular Forms", topicId=topicID)
    subTopic.objects.create(subTopicName="Angular Modules", topicId=topicID)
    subTopic.objects.create(subTopicName="Building & Deploying With CLI", topicId=topicID)
 
    topicID=topic.objects.get(topicId=1009)
    subTopic.objects.create(subTopicName="Stored Procedure And Function", topicId=topicID)
    subTopic.objects.create(subTopicName="Cursor", topicId=topicID)
    subTopic.objects.create(subTopicName="Triggers", topicId=topicID)
    subTopic.objects.create(subTopicName="MongoDB - CRUD Operations", topicId=topicID)
    
# def uploadData2(request):


    topicIds=subTopic.objects.get(subTopicId=10001)
    lecture.objects.create(lectureId= 100001, lectureName="What is Computer Program?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Categories of Programming Language", subTopicId=topicIds)
    lecture.objects.create(lectureName="High Level Language Vs Low Level Language", subTopicId=topicIds)
    lecture.objects.create(lectureName="Computer Instruction Components", subTopicId=topicIds)
    lecture.objects.create(lectureName="Programming Language", subTopicId=topicIds)
    lecture.objects.create(lectureName="Compiler Vs Interpreter", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is Instruction in Computer?", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is Program?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10002)
    lecture.objects.create(lectureName="Decision Making statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comparison Operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Logical Operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="AND Operator and OR operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of IF condition and its Flowcharts", subTopicId=topicIds)
    lecture.objects.create(lectureName="Nested IF condition and Its flowchart", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10003)
    lecture.objects.create(lectureName="Iterative Statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Infinite and Finite Loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="Flowchart to print 1 to 10 numbers", subTopicId=topicIds)
    lecture.objects.create(lectureName="If vs Loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="Factorial of Given Number", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10004)
    lecture.objects.create(lectureName="What is data and information", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is Database", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is Database Management System", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is SQL?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="E-R Diagram.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Geometric Shapes in ER diagram", subTopicId=topicIds)
    lecture.objects.create(lectureName="Component of ER diagram.[Entity,Attribute and Relationship]", subTopicId=topicIds)
    lecture.objects.create(lectureName="Relationship", subTopicId=topicIds)
    lecture.objects.create(lectureName="ER diagram to Table Conversion", subTopicId=topicIds)
    lecture.objects.create(lectureName="workbench", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10005)
    lecture.objects.create(lectureName="Data types, expressions, operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Data Definition Language(DDL)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creation of table", subTopicId=topicIds)
    lecture.objects.create(lectureName="Dropping a table", subTopicId=topicIds)
    lecture.objects.create(lectureName="Working with different options", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10006)
    lecture.objects.create(lectureName="INSERT statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="UPDATE statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="DELETE statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Constraints", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10007)
    lecture.objects.create(lectureName="SELECT statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="WHERE clause search condition", subTopicId=topicIds)
    lecture.objects.create(lectureName="Arithmetic, Comparison and Logical operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Range operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="List operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Like operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using ORDER BY, DISTINCT and TOP", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using IS NULL and IS NOT NULL", subTopicId=topicIds)
    lecture.objects.create(lectureName="Various other clauses", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10008)
    lecture.objects.create(lectureName="String Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Math Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Date Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Aggregate Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="GROUP BY clause with HAVING", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10009)
    lecture.objects.create(lectureName="Introduction to Joins", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of Joins", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction Types of Sub-queries", subTopicId=topicIds)
    lecture.objects.create(lectureName="Search Condition", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comparison operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="IN", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10010)
    lecture.objects.create(lectureName="Client Server Architecture", subTopicId=topicIds)
    lecture.objects.create(lectureName="HTML Structure-Head,Body and HTML Version", subTopicId=topicIds)
    lecture.objects.create(lectureName="HTML Comments", subTopicId=topicIds)
    lecture.objects.create(lectureName="Page Information-title,meta,link,style, script", subTopicId=topicIds)
    lecture.objects.create(lectureName="HTML Tags and Attributes", subTopicId=topicIds)
    lecture.objects.create(lectureName="First Web page - Hello World", subTopicId=topicIds)
    lecture.objects.create(lectureName="Block Elements - Header tag, Paragraph tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="Format tag - bold, strong, italics, em, underline, del, sub, sup", subTopicId=topicIds)
    lecture.objects.create(lectureName="Document structure - Div tag, Span tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="anchor tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="image tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="List - Ordered, unordered, defination", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10011)
    lecture.objects.create(lectureName="Table structure-tr,td,th,colspan and rowspan", subTopicId=topicIds)
    lecture.objects.create(lectureName="Form tag and Form Elements - Input type, textarea, select", subTopicId=topicIds)
    lecture.objects.create(lectureName="fieldset tag, legend tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10012)
    lecture.objects.create(lectureName="Need of CSS", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of CSS", subTopicId=topicIds)
    lecture.objects.create(lectureName="comments in CSS", subTopicId=topicIds)
    lecture.objects.create(lectureName="tag selector", subTopicId=topicIds)
    lecture.objects.create(lectureName="id selector", subTopicId=topicIds)
    lecture.objects.create(lectureName="class Selector", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10013)
    lecture.objects.create(lectureName="Color property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Text property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Font property", subTopicId=topicIds)
    lecture.objects.create(lectureName="box property (width and Height)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Display Property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Background- property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10014)
    lecture.objects.create(lectureName="Introduction to Javascript", subTopicId=topicIds)
    lecture.objects.create(lectureName="Variables using var, let & const", subTopicId=topicIds)
    lecture.objects.create(lectureName="Functions in Javascript", subTopicId=topicIds)
    lecture.objects.create(lectureName="Conditional Statements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Looping", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10015)
    lecture.objects.create(lectureName="Working on fetch function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating currency convertor by consuming API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10016)
    lecture.objects.create(lectureName="What is Python?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Features of Python", subTopicId=topicIds)
    lecture.objects.create(lectureName="Installation of Python", subTopicId=topicIds)
    lecture.objects.create(lectureName="variables in Python", subTopicId=topicIds)
    lecture.objects.create(lectureName="print() function | Message printing & Variable Value Printing", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comments in Python", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10017)
    lecture.objects.create(lectureName="What is Data?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Basic Data types in Python-Number,string and Boolean", subTopicId=topicIds)
    lecture.objects.create(lectureName="type() to check datatype", subTopicId=topicIds)
    lecture.objects.create(lectureName="Arithmetic Operator [+,-,/,*,//,%]", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="taking input from user | input() , string to int conversion using int() function , string to float conversion using float() function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10018)
    lecture.objects.create(lectureName="Need of Conditional Statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comparison Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="if...else statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="logical operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="elif statements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Indentation in Python", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10019)
    lecture.objects.create(lectureName="range() function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Need of Loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="for loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="while loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="Continue, break and pass keyword", subTopicId=topicIds)
    lecture.objects.create(lectureName="Nested loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10020)
    lecture.objects.create(lectureName="String", subTopicId=topicIds)
    lecture.objects.create(lectureName="List", subTopicId=topicIds)
    lecture.objects.create(lectureName="Multidimensional List | tuple , set", subTopicId=topicIds)
    lecture.objects.create(lectureName="Dictionary", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10021)
    lecture.objects.create(lectureName="Simulator to WordScapes on Play Store", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10022)
    lecture.objects.create(lectureName="Defining and calling function", subTopicId=topicIds)
    lecture.objects.create(lectureName="return statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of Argument-default,variable length", subTopicId=topicIds)
    lecture.objects.create(lectureName="Variable Scope - Global vs Local", subTopicId=topicIds)
    lecture.objects.create(lectureName="Recursive function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Need of Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Built in Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="User defined Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Packages", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10023)
    lecture.objects.create(lectureName="Word count and writting the word count to different file", subTopicId=topicIds)
    lecture.objects.create(lectureName="File operations", subTopicId=topicIds)
    lecture.objects.create(lectureName="Need of file", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is file", subTopicId=topicIds)
    lecture.objects.create(lectureName="Modes in file (read, write, append)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Methods in file operations", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10024)
    lecture.objects.create(lectureName="Introduction to OOP -Classes & Objects s", subTopicId=topicIds)
    lecture.objects.create(lectureName="Methods and attributes (user defined method)", subTopicId=topicIds)
    lecture.objects.create(lectureName="constructor and destructor", subTopicId=topicIds)
    lecture.objects.create(lectureName="Inheritance and its types", subTopicId=topicIds)
    lecture.objects.create(lectureName="Operator overloading", subTopicId=topicIds)
    lecture.objects.create(lectureName="Exception Handling[try,except,finally)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10025)
    lecture.objects.create(lectureName="What is Framework", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is Django Framework", subTopicId=topicIds)
    lecture.objects.create(lectureName="Need of Django Framework (Features of Django)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Installation - Python, Virtualenv, Django", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10026)
    lecture.objects.create(lectureName="Introduction to the Pet Store Project", subTopicId=topicIds)
    lecture.objects.create(lectureName="SDLC", subTopicId=topicIds)
    lecture.objects.create(lectureName="Agile Methodology", subTopicId=topicIds)
    lecture.objects.create(lectureName="Scrum", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction to JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10027)
    lecture.objects.create(lectureName="Django First Project", subTopicId=topicIds)
    lecture.objects.create(lectureName="Django Architecture", subTopicId=topicIds)
    lecture.objects.create(lectureName="Django view", subTopicId=topicIds)
    lecture.objects.create(lectureName="URL Mapping", subTopicId=topicIds)
    lecture.objects.create(lectureName="Function Based Views", subTopicId=topicIds)
    lecture.objects.create(lectureName="Class Based Views", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10028)
    lecture.objects.create(lectureName="Your first app Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding CRUD", subTopicId=topicIds)
    lecture.objects.create(lectureName="Product Model", subTopicId=topicIds)
    lecture.objects.create(lectureName="Django Admin", subTopicId=topicIds)
    lecture.objects.create(lectureName="List View", subTopicId=topicIds)
    lecture.objects.create(lectureName="Detail View", subTopicId=topicIds)
    lecture.objects.create(lectureName="ImageField & FileField", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding Lookups", subTopicId=topicIds)
    lecture.objects.create(lectureName="Custom Model Managers", subTopicId=topicIds)
    lecture.objects.create(lectureName="Featured & Custom QuerySets", subTopicId=topicIds)
    lecture.objects.create(lectureName="SlugField & Signals", subTopicId=topicIds)
    lecture.objects.create(lectureName="Products URLs", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10029)
    lecture.objects.create(lectureName="Base Template", subTopicId=topicIds)
    lecture.objects.create(lectureName="Include Tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="Pass Arguments with Include", subTopicId=topicIds)
    lecture.objects.create(lectureName="Reusable List View Snippets", subTopicId=topicIds)
    lecture.objects.create(lectureName="Reverse for URLs", subTopicId=topicIds)
    lecture.objects.create(lectureName="Navbar", subTopicId=topicIds)
    lecture.objects.create(lectureName="Template Filters", subTopicId=topicIds)
    lecture.objects.create(lectureName="ForLoop Counter & Cycle", subTopicId=topicIds)
    lecture.objects.create(lectureName="Template Inheritance/ Template Extending", subTopicId=topicIds)
    lecture.objects.create(lectureName="static files", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10030)
    lecture.objects.create(lectureName="Adding Bootstrap", subTopicId=topicIds)
    lecture.objects.create(lectureName="Container vs Container-Fluid", subTopicId=topicIds)
    lecture.objects.create(lectureName="Rows And Columns", subTopicId=topicIds)
    lecture.objects.create(lectureName="Column Sizing", subTopicId=topicIds)
    lecture.objects.create(lectureName="Desinging for Different Browser Sizes with Breakpoints", subTopicId=topicIds)
    lecture.objects.create(lectureName="Spacing with Margin & Padding", subTopicId=topicIds)
    lecture.objects.create(lectureName="Navbar", subTopicId=topicIds)
    lecture.objects.create(lectureName="Integrate to Django", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10031)
    lecture.objects.create(lectureName="A Basic Search View", subTopicId=topicIds)
    lecture.objects.create(lectureName="Display the Query to the User", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating the Search Form", subTopicId=topicIds)
    lecture.objects.create(lectureName="Better Lookups with Q", subTopicId=topicIds)
    lecture.objects.create(lectureName="Tag Component", subTopicId=topicIds)
    lecture.objects.create(lectureName="Shell Commands for a Brief Intro to Foreign Keys", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10032)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Django Sessions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Cart Model", subTopicId=topicIds)
    lecture.objects.create(lectureName="Cart Update View", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add to Cart Form", subTopicId=topicIds)
    lecture.objects.create(lectureName="Display Cart", subTopicId=topicIds)
    lecture.objects.create(lectureName="Remove Items from the Cart", subTopicId=topicIds)
    lecture.objects.create(lectureName="Cart Icon & FontAwesome", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10033)
    lecture.objects.create(lectureName="The Roadmap for the Checkout Process", subTopicId=topicIds)
    lecture.objects.create(lectureName="Generate the Order ID", subTopicId=topicIds)
    lecture.objects.create(lectureName="Review Order Payment Page", subTopicId=topicIds)
    lecture.objects.create(lectureName="PayPal Payment Gateway with Sandbox Account", subTopicId=topicIds)
    lecture.objects.create(lectureName="Integrate PayPal", subTopicId=topicIds)
    lecture.objects.create(lectureName="move cart items to OrderPet model", subTopicId=topicIds)
    lecture.objects.create(lectureName="store order detail in backend.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Send Order confirmation Email and order success page.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10034)
    lecture.objects.create(lectureName="User registration using built auth app.", subTopicId=topicIds)
    lecture.objects.create(lectureName="user login", subTopicId=topicIds)
    lecture.objects.create(lectureName="user logout", subTopicId=topicIds)
    lecture.objects.create(lectureName="Authentcation and Autherization", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10035)
    lecture.objects.create(lectureName="Create Repository on GitHub and upload project..", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10036)
    lecture.objects.create(lectureName="Why test?", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is testing, types of testing", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assertions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Basic pytest installation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10037)
    lecture.objects.create(lectureName="Resume Basics", subTopicId=topicIds)
    lecture.objects.create(lectureName="Writing Rules", subTopicId=topicIds)
    lecture.objects.create(lectureName="HR Friendly Resumes", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10038)
    lecture.objects.create(lectureName="Introduction to Web Portfolio ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Donot Start From Scratch", subTopicId=topicIds)
    lecture.objects.create(lectureName="Publishing to the Web", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction to Video Resumes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Profile Optimization and Networking on LinkedIn", subTopicId=topicIds)
    lecture.objects.create(lectureName="Showcasing Projects on Github", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10039)
    lecture.objects.create(lectureName="Common Interview Stages ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Communication Skills", subTopicId=topicIds)
    lecture.objects.create(lectureName="Popular Interview Questions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Tricky Interview Questions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Technical Interview Preparation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Aptitude Test Overview", subTopicId=topicIds)
    lecture.objects.create(lectureName="Interview Day Checklist", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10040)
    lecture.objects.create(lectureName="Job Search Resources ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding Job Descriptions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Company Research", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10041)
    lecture.objects.create(lectureName="What is Cloud Computing?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Traditional IT structure vs Cloud Services", subTopicId=topicIds)
    lecture.objects.create(lectureName="Identity Access Management", subTopicId=topicIds)
    lecture.objects.create(lectureName="MFA Authentication", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS CloudShell Setup", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10042)
    lecture.objects.create(lectureName="Amazon Elastic Cloud Compute ( EC2 ) ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon EC2 Auto Scaling", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Lightsail", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Elastic Beanstalk", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Lambda", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10043)
    lecture.objects.create(lectureName="Amazon Elastic Block Store ( EBS ) ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Elastic File System ( EFS )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Simple Storage Service ( S3 )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon S3 Glacier", subTopicId=topicIds)
    lecture.objects.create(lectureName="Storage Gateway", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10044)
    lecture.objects.create(lectureName="ELB Overview ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Classic Load Balancer ( CLB )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Application Load Balancer ( ALB )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Network Load Balancer ( NLB )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10045)
    lecture.objects.create(lectureName="Amazon Databases Overview ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Aurora", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon ElasticCache", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon DynamoDB", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Relational Database Service ( RDS )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Neptune", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10046)
    lecture.objects.create(lectureName="Route53 Introduction ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Route53 as a Registrar", subTopicId=topicIds)
    lecture.objects.create(lectureName="Record Sets & Routing Policies", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10047)
    lecture.objects.create(lectureName="CloudFormation ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Elastic BeanStalk", subTopicId=topicIds)
    lecture.objects.create(lectureName="CodeDeploy, CodeCommit, CodeBuild, CodePipeline, CodeArtifact", subTopicId=topicIds)
    lecture.objects.create(lectureName="Systems Manager ( SSM )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10048)
    lecture.objects.create(lectureName="Amazon API Gateway ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon EventBridge", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Simple Notification Service ( SNS )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon Simple Queue Service ( SQS )", subTopicId=topicIds)
    lecture.objects.create(lectureName="Amazon MQ", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Step Functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10049)
    lecture.objects.create(lectureName="CloudWatch ", subTopicId=topicIds)
    lecture.objects.create(lectureName="CloudTrial", subTopicId=topicIds)
    lecture.objects.create(lectureName="CloudGuru", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10050)
    lecture.objects.create(lectureName="Virtual Private Cloud ( VPC ) ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Security Groups & NACL", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10051)
    lecture.objects.create(lectureName="Encryption with KMS ", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Certificate Manager", subTopicId=topicIds)
    lecture.objects.create(lectureName="DDoS Protection : WAF & Shield", subTopicId=topicIds)
    lecture.objects.create(lectureName="Artifact and GuardDuty Overview", subTopicId=topicIds)
    lecture.objects.create(lectureName="Config Overview", subTopicId=topicIds)
    lecture.objects.create(lectureName="Security Hub and Root User Privileges", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10052)
    lecture.objects.create(lectureName="Elastic Container Service ( ECS ) ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Elastic Kubernetes Service ( EKS )", subTopicId=topicIds)
    lecture.objects.create(lectureName="CloudFront", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Sagemaker", subTopicId=topicIds)
    lecture.objects.create(lectureName="AWS Sumerian", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10053)
    lecture.objects.create(lectureName="Introduction", subTopicId=topicIds)
    lecture.objects.create(lectureName="Java Features", subTopicId=topicIds)
    lecture.objects.create(lectureName="Java Virtual Machine - Architecture, Compiled vs Interpreted", subTopicId=topicIds)
    lecture.objects.create(lectureName="Languages, Bytecode and Object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Java Installation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Basic Concepts of OOPs", subTopicId=topicIds)
    lecture.objects.create(lectureName="First Java Program", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10054)
    lecture.objects.create(lectureName="Data Types", subTopicId=topicIds)
    lecture.objects.create(lectureName="Type Casting", subTopicId=topicIds)
    lecture.objects.create(lectureName="Variables", subTopicId=topicIds)
    lecture.objects.create(lectureName="Constants", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comments", subTopicId=topicIds)
    lecture.objects.create(lectureName="Command Line Arguments", subTopicId=topicIds)
    lecture.objects.create(lectureName="Identifiers", subTopicId=topicIds)
    lecture.objects.create(lectureName="Literals", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10055)
    lecture.objects.create(lectureName="Arithmetic Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Relational Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Bitwise Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Logical Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Ternary Operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Unary Operator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Operator Precedence in Java", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment ", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10056)
    lecture.objects.create(lectureName="if statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="if...else statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Nested if...else statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="switch statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="for loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="while loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="do...while loop", subTopicId=topicIds)
    lecture.objects.create(lectureName="Use of break and continue", subTopicId=topicIds)
    lecture.objects.create(lectureName="Logical Programs", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10057)
    lecture.objects.create(lectureName="Declaring and Initializing an Array", subTopicId=topicIds)
    lecture.objects.create(lectureName="Accessing Array elements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Iterating over Array", subTopicId=topicIds)
    lecture.objects.create(lectureName="Multidimensional Array", subTopicId=topicIds)
    lecture.objects.create(lectureName="Logical Programs using Array", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10058)
    lecture.objects.create(lectureName="Simulator to WordScapes on Play Store", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10059)
    lecture.objects.create(lectureName="Classes & Object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Methods - Passing parameters to methods, return type", subTopicId=topicIds)
    lecture.objects.create(lectureName="Object as parameters, Constructors & Destructor, var-args", subTopicId=topicIds)
    lecture.objects.create(lectureName="Access & Non-Access Modifiers", subTopicId=topicIds)
    lecture.objects.create(lectureName="Dynamic memory allocation, Garbage collection and finalize()", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Packages and Class Hierarchy", subTopicId=topicIds)
    lecture.objects.create(lectureName="Object Class, Import statement, Built-in packages, User defined packages", subTopicId=topicIds)
    lecture.objects.create(lectureName="Nested & Anonymous Class", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10060)
    lecture.objects.create(lectureName="What is Inheritance?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of Inheritance", subTopicId=topicIds)
    lecture.objects.create(lectureName="Why we use Inheritance", subTopicId=topicIds)
    lecture.objects.create(lectureName="Method Overriding", subTopicId=topicIds)
    lecture.objects.create(lectureName="Method Overloading", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Abstract Classes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Interfaces", subTopicId=topicIds)
    lecture.objects.create(lectureName="Polymorphism", subTopicId=topicIds)
    lecture.objects.create(lectureName="default, static and private methods in interface", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10061)
    lecture.objects.create(lectureName="Various ways to create String in Java", subTopicId=topicIds)
    lecture.objects.create(lectureName="In-built String functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="StringBuffer", subTopicId=topicIds)
    lecture.objects.create(lectureName="StringBuilder", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Difference between String, StringBuffer & StringBuilder", subTopicId=topicIds)
    lecture.objects.create(lectureName="Logical Programs on Strings", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10062)
    lecture.objects.create(lectureName="What is Exception and Handling an Exception", subTopicId=topicIds)
    lecture.objects.create(lectureName="Compile time errors & Run time errors", subTopicId=topicIds)
    lecture.objects.create(lectureName="try...catch...finally", subTopicId=topicIds)
    lecture.objects.create(lectureName="throw & throws keywords", subTopicId=topicIds)
    lecture.objects.create(lectureName="User Defined Exception", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10063)
    lecture.objects.create(lectureName="FileInputStream & FileOutputStream", subTopicId=topicIds)
    lecture.objects.create(lectureName="FileReader & FileWriter", subTopicId=topicIds)
    lecture.objects.create(lectureName="Serialization", subTopicId=topicIds)
    lecture.objects.create(lectureName="Object serialization, transient", subTopicId=topicIds)
    lecture.objects.create(lectureName="Wrapper Classes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Autoboxing and Unboxing", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10064)
    lecture.objects.create(lectureName="Introduction to Collection", subTopicId=topicIds)
    lecture.objects.create(lectureName="Collection Hierarchy", subTopicId=topicIds)
    lecture.objects.create(lectureName="Working with ArrayList, LinkedList, HashSet, LinkedHashSet, TreeSet, Queue, Dequeue, Stack", subTopicId=topicIds)
    lecture.objects.create(lectureName="Maps - HashMap, LinkedHashMap, TreeMap", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using Iterators and Enumerations, ListIterator, forEach()", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Generics", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comparable and Comparators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Functional Interfaces - Lambda Expressions", subTopicId=topicIds)
    lecture.objects.create(lectureName="forEach() method in Iterable Interface", subTopicId=topicIds)
    lecture.objects.create(lectureName="Streams - Sequential, Parallel", subTopicId=topicIds)
    lecture.objects.create(lectureName="Filtering Collections", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10065)
    lecture.objects.create(lectureName="Word count and writing the word count to different file", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10066)
    lecture.objects.create(lectureName="Introduction Multi-Threading", subTopicId=topicIds)
    lecture.objects.create(lectureName="Thread Life Cycle", subTopicId=topicIds)
    lecture.objects.create(lectureName="Thread Class vs Runnable Interface", subTopicId=topicIds)
    lecture.objects.create(lectureName="Synchronized Methods, Block", subTopicId=topicIds)
    lecture.objects.create(lectureName="Daemon Thread", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10067)
    lecture.objects.create(lectureName="Java Time API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Project on Stop Watch", subTopicId=topicIds)
    lecture.objects.create(lectureName="Java Http Client API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Project on Currency Convertor", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10068)
    lecture.objects.create(lectureName="IoC Container", subTopicId=topicIds)
    lecture.objects.create(lectureName="Beans Overview", subTopicId=topicIds)
    lecture.objects.create(lectureName="Dependency Injection", subTopicId=topicIds)
    lecture.objects.create(lectureName="Aspect Oriented Programming (AOP)", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10069)
    lecture.objects.create(lectureName="Spring MVC", subTopicId=topicIds)
    lecture.objects.create(lectureName="Request-Response Life Cycle", subTopicId=topicIds)
    lecture.objects.create(lectureName="Terminologies & Pre-requisites", subTopicId=topicIds)
    lecture.objects.create(lectureName="Tools", subTopicId=topicIds)
    lecture.objects.create(lectureName="Components of Spring MVC", subTopicId=topicIds)
    lecture.objects.create(lectureName="Basics of Maven", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create a Project in Maven", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create jar package file using Maven Command", subTopicId=topicIds)
    lecture.objects.create(lectureName="Maven Commands", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10070)
    lecture.objects.create(lectureName="Introduction to the Pet Store Project", subTopicId=topicIds)
    lecture.objects.create(lectureName="SDLC", subTopicId=topicIds)
    lecture.objects.create(lectureName="Agile Methodology", subTopicId=topicIds)
    lecture.objects.create(lectureName="Scrum", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction to JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10071)
    lecture.objects.create(lectureName="Download & Install Spring Tool 4", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating and Running Spring Boot Application using ST4 - Pet Store Project", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction to Properties file and changing some default properties like application name, port, etc.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Git Project Creation & Doing Initial Commit", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10072)
    lecture.objects.create(lectureName="What is REST?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating our First REST API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Adding DevTools", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Service file for Product Resource using in-memory data", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Rest Controller CRUD Operations on Product Resource", subTopicId=topicIds)
    lecture.objects.create(lectureName="Consuming REST APIs using any Rest Client Library like postman, hoppscotch, etc.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10073)
    lecture.objects.create(lectureName="Adding spring boot starter validation dependency", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add built-in validators to our User Resource Model", subTopicId=topicIds)
    lecture.objects.create(lectureName="Validating the Request using @Valid annotation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating custom field validator for phoneNumber", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create custom cross-field validator for password & confirmPassword", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10074)
    lecture.objects.create(lectureName="Create database user & database", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add mysql connector & spring jpa dependency in our Spring Application", subTopicId=topicIds)
    lecture.objects.create(lectureName="Adding mysql configuration details in application.properties file", subTopicId=topicIds)
    lecture.objects.create(lectureName="Convert Product model to Entity by using JPA annotations", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create JPA repository for Product entity", subTopicId=topicIds)
    lecture.objects.create(lectureName="Modifying service file to use repository instead of in-memory data", subTopicId=topicIds)
    lecture.objects.create(lectureName="Defining Custom Query Methods in Repository", subTopicId=topicIds)
    lecture.objects.create(lectureName="JPA Auditing using @CreatedDate and @LastModifiedDate", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10075)
    lecture.objects.create(lectureName="Add Spring Data REST Starter Dependency", subTopicId=topicIds)
    lecture.objects.create(lectureName="Remove not needed APIs from controllers", subTopicId=topicIds)
    lecture.objects.create(lectureName="Make necessary changes for validation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Pagination & Sorting using PagingAndSortingRepository", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10076)
    lecture.objects.create(lectureName="Create OneToOne Mapping for User & Address", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create OneToMany & ManyToOne Mapping for Category & Products", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create ManyToMany Mapping for Orders & Products", subTopicId=topicIds)
    lecture.objects.create(lectureName="Consuming all the APIs with relationships", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create Projections & Excerpts for necessary data", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10077)
    lecture.objects.create(lectureName="What is Authentication & Authorization", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add Spring Security Starter Dependency", subTopicId=topicIds)
    lecture.objects.create(lectureName="Authentication based on default security config", subTopicId=topicIds)
    lecture.objects.create(lectureName="Change default username and password", subTopicId=topicIds)
    lecture.objects.create(lectureName="Change default url configs using HttpSecurity", subTopicId=topicIds)
    lecture.objects.create(lectureName="Allow certain URLs based on http methods and url patterns", subTopicId=topicIds)
    lecture.objects.create(lectureName="Override default authentication manager by providing inMemoryAuthentication", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add roles to the user", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add security to particular URL based on user's role using hasRole() method", subTopicId=topicIds)
    lecture.objects.create(lectureName="Authorization using @PreAuthorize, @RolesAllowed or @Secured", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10078)
    lecture.objects.create(lectureName="User Registration Flow", subTopicId=topicIds)
    lecture.objects.create(lectureName="Use UserDetails interface to implement User object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create custom MyUserDetailsService using UserDetailsService class and override loadUserByUsername method", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add MyUserDetailsService object in security configuration for authentication", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Login API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10079)
    lecture.objects.create(lectureName="Create API to upload image for a product", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create API to download image of a product", subTopicId=topicIds)
    lecture.objects.create(lectureName="Commit whatever is done to Git Project & mark tasks as Done in JIRA", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10080)
    lecture.objects.create(lectureName="Create simple frontend application using HTML, CSS and Javascript", subTopicId=topicIds)
    lecture.objects.create(lectureName="Consume Product APIs using fetch function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Displaying fetched data in HTML page", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10081)
    lecture.objects.create(lectureName="The JUnit framework", subTopicId=topicIds)
    lecture.objects.create(lectureName="How to define a test in JUnit?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Writing test case for the API", subTopicId=topicIds)
    lecture.objects.create(lectureName="Run your test from the command line", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10082)
    lecture.objects.create(lectureName="Creating jar file", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using various environments using properties file", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10083)
    lecture.objects.create(lectureName="Sementic Elements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Audio,Video Tag", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10084)
    lecture.objects.create(lectureName="Margin and Padding", subTopicId=topicIds)
    lecture.objects.create(lectureName="Shadow Property-Text and Box", subTopicId=topicIds)
    lecture.objects.create(lectureName="Float and Clear", subTopicId=topicIds)
    lecture.objects.create(lectureName="Position Property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment ", subTopicId=topicIds)
 
    topicIds=subTopic.objects.get(subTopicId=10085)
    lecture.objects.create(lectureName="Background Gradient", subTopicId=topicIds)
    lecture.objects.create(lectureName="Transform Properties", subTopicId=topicIds)
    lecture.objects.create(lectureName="Transition properties", subTopicId=topicIds)
    lecture.objects.create(lectureName="Keyframe Animation", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10086)
    lecture.objects.create(lectureName="Fixed Vs Fluid Vs Adaptive Vs Responsive layout", subTopicId=topicIds)
    lecture.objects.create(lectureName="Meta Viewport", subTopicId=topicIds)
    lecture.objects.create(lectureName="Media Queries", subTopicId=topicIds)
    lecture.objects.create(lectureName="Responsive Images", subTopicId=topicIds)
    lecture.objects.create(lectureName="Flexbox Layout", subTopicId=topicIds)
    lecture.objects.create(lectureName="Grid Layout", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10087)
    lecture.objects.create(lectureName="Javascript History and Features", subTopicId=topicIds)
    lecture.objects.create(lectureName="Types of JS", subTopicId=topicIds)
    lecture.objects.create(lectureName="Print Hello World", subTopicId=topicIds)
    lecture.objects.create(lectureName="Comments in Javascript", subTopicId=topicIds)
    lecture.objects.create(lectureName="Browser Console", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10088)
    lecture.objects.create(lectureName="var, let and const keywords Scopes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Variable Hoisting", subTopicId=topicIds)
    lecture.objects.create(lectureName="Datatypes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10089)
    lecture.objects.create(lectureName="Conditional Statements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Control Statements", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10090)
    lecture.objects.create(lectureName="Built-in Functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Regular Functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Passing Parameters to Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="return value", subTopicId=topicIds)
    lecture.objects.create(lectureName="Anonymous Functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Arrow Functions", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10091)
    lecture.objects.create(lectureName="Defining Objects", subTopicId=topicIds)
    lecture.objects.create(lectureName="Accessing Properties and Methods of the Object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Usage of 'this' keyword", subTopicId=topicIds)
    lecture.objects.create(lectureName="Objects inside Object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Arrays in Javascript", subTopicId=topicIds)
    lecture.objects.create(lectureName="String and math Object", subTopicId=topicIds)
    lecture.objects.create(lectureName="Window Object - Console,Screen, Location, History", subTopicId=topicIds)
    lecture.objects.create(lectureName="Dynamic Property Syntax in Object Literal", subTopicId=topicIds)
    lecture.objects.create(lectureName="Shorter Property Syntax in Object Literal", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10092)
    lecture.objects.create(lectureName="DOM Property Manipulation", subTopicId=topicIds)
    lecture.objects.create(lectureName="DOM Event Handling", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10093)
    lecture.objects.create(lectureName="Bootstrap Introduction", subTopicId=topicIds)
    lecture.objects.create(lectureName="Layout and Content", subTopicId=topicIds)
    lecture.objects.create(lectureName="Bootstrap components", subTopicId=topicIds)
    lecture.objects.create(lectureName="Bootstrap utilities", subTopicId=topicIds)
    lecture.objects.create(lectureName="Bootstrap icons", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10094)
    lecture.objects.create(lectureName="What Is Angular?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Prerequisites", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is TypeScript?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Walk through of sample project", subTopicId=topicIds)
    lecture.objects.create(lectureName="Angular Installation & Setting up environment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Anatomy of Angular Application", subTopicId=topicIds)
    lecture.objects.create(lectureName="Running Angular Application", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10095)
    lecture.objects.create(lectureName="What is an Angular Module? ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Introduction to Components", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding the role of AppModule & Component Declaration", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating component using CLI", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using the component in application", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding metadata", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating component manually", subTopicId=topicIds)
    lecture.objects.create(lectureName="Defining template and css style", subTopicId=topicIds)
    lecture.objects.create(lectureName="Adding bootstrap for styling", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10096)
    lecture.objects.create(lectureName="Interpolation & Normal Property Binding ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Property Binding - Class & Style", subTopicId=topicIds)
    lecture.objects.create(lectureName="Event Binding", subTopicId=topicIds)
    lecture.objects.create(lectureName="Two-Way Data Binding", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10097)
    lecture.objects.create(lectureName="Assigning types to variables ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating custom types for objects", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using setters and getters of typescript to filter data", subTopicId=topicIds)
    lecture.objects.create(lectureName="Transforming data using built-in Pipes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Custom Pipe", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10098)
    lecture.objects.create(lectureName="Understanding Directives ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Attribute Directives", subTopicId=topicIds)
    lecture.objects.create(lectureName="Understanding Structural Directives: ngIf and ngFor", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating attribute directive", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10099)
    lecture.objects.create(lectureName="Building Nested Components ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Passing data to child component using @Input", subTopicId=topicIds)
    lecture.objects.create(lectureName="Passing data to parent component using @Output", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10100)
    lecture.objects.create(lectureName="Why would you Need Services? ", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is dependency injection", subTopicId=topicIds)
    lecture.objects.create(lectureName="Building a Service", subTopicId=topicIds)
    lecture.objects.create(lectureName="Registering a Service", subTopicId=topicIds)
    lecture.objects.create(lectureName="Injecting the Service", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10101)
    lecture.objects.create(lectureName="Introduction to RxJS - Observables and Operators ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Difference between Promises and Observables", subTopicId=topicIds)
    lecture.objects.create(lectureName="Sending HTTP Request", subTopicId=topicIds)
    lecture.objects.create(lectureName="Retrieving data using HTTP", subTopicId=topicIds)
    lecture.objects.create(lectureName="Exception Handling", subTopicId=topicIds)
    lecture.objects.create(lectureName="Unsubscribing observables", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using async pipe", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Observables using of() function & Observable class", subTopicId=topicIds)
    lecture.objects.create(lectureName="Handle observable errors and complete", subTopicId=topicIds)
    lecture.objects.create(lectureName="Perform operations using Operators", subTopicId=topicIds)
    lecture.objects.create(lectureName="Subject & BehaviorSubject", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10102)
    lecture.objects.create(lectureName="What is SPA? ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add RouterModule", subTopicId=topicIds)
    lecture.objects.create(lectureName="Add Routes for every Route", subTopicId=topicIds)
    lecture.objects.create(lectureName="Specify router-outlet for the route to be displayed", subTopicId=topicIds)
    lecture.objects.create(lectureName="Specify router links using routerLink", subTopicId=topicIds)
    lecture.objects.create(lectureName="Specify the active route class using routerLinkActive", subTopicId=topicIds)
    lecture.objects.create(lectureName="Specify title for every route using title property", subTopicId=topicIds)
    lecture.objects.create(lectureName="Get query parameters from the route", subTopicId=topicIds)
    lecture.objects.create(lectureName="Get path params from the route", subTopicId=topicIds)
    lecture.objects.create(lectureName="Navigate to route programmatically", subTopicId=topicIds)
    lecture.objects.create(lectureName="Handling route navigation on the same route with different dynamic parameters", subTopicId=topicIds)
    lecture.objects.create(lectureName="Preventing unauthorized access to any route using guards", subTopicId=topicIds)
    lecture.objects.create(lectureName="Nested child routes", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10103)
    lecture.objects.create(lectureName="How does the Angular form work? ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Different ways for creating forms", subTopicId=topicIds)
    lecture.objects.create(lectureName="Difference between template driven and reactive forms", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create template driven form", subTopicId=topicIds)
    lecture.objects.create(lectureName="Validation in template driven forms", subTopicId=topicIds)
    lecture.objects.create(lectureName="Create reactive form", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using FormBuilder service", subTopicId=topicIds)
    lecture.objects.create(lectureName="Validation in reactive forms", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating custom validator", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10104)
    lecture.objects.create(lectureName="What is Angular Module ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Feature Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Shared Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Routing Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating Lazy Loaded Module", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10105)
    lecture.objects.create(lectureName="ng generate ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Creating production build using `ng build`", subTopicId=topicIds)
    lecture.objects.create(lectureName="Deploying application to Github Pages", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10106)
    lecture.objects.create(lectureName="Introduction to Stored Procedure", subTopicId=topicIds)
    lecture.objects.create(lectureName="Variables and datatypes", subTopicId=topicIds)
    lecture.objects.create(lectureName="conditional Statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)
    lecture.objects.create(lectureName="Looping Statement", subTopicId=topicIds)
    lecture.objects.create(lectureName="Stored Function", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10107)
    lecture.objects.create(lectureName="Introduction to Cursor and Types of cursor ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Explicit Cursor", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10108)
    lecture.objects.create(lectureName="Introduction to Triggers ", subTopicId=topicIds)
    lecture.objects.create(lectureName="Row level Trigger", subTopicId=topicIds)
    lecture.objects.create(lectureName="Statement Level Trigger", subTopicId=topicIds)
    lecture.objects.create(lectureName="Before Trigger", subTopicId=topicIds)
    lecture.objects.create(lectureName="After Trigger", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    topicIds=subTopic.objects.get(subTopicId=10109)
    lecture.objects.create(lectureName="Difference between SQL and NoSQL ", subTopicId=topicIds)
    lecture.objects.create(lectureName="What is MongoDB?", subTopicId=topicIds)
    lecture.objects.create(lectureName="Installing MongoDB on local machine", subTopicId=topicIds)
    lecture.objects.create(lectureName="Data Types in MongoDB", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using MongoDB Shell", subTopicId=topicIds)
    lecture.objects.create(lectureName="Perform CRUD Operations in MongoDB", subTopicId=topicIds)
    lecture.objects.create(lectureName="Finding Documents", subTopicId=topicIds)
    lecture.objects.create(lectureName="Using Projection to get required fields from collection", subTopicId=topicIds)
    lecture.objects.create(lectureName="Various MongoDB operators like $sort, $limit, $set, etc.", subTopicId=topicIds)
    lecture.objects.create(lectureName="Aggregates in MongoDB Queries", subTopicId=topicIds)
    lecture.objects.create(lectureName="Assignment", subTopicId=topicIds)

    jobLocationAvailable.objects.create(location="Thane")
    jobLocationAvailable.objects.create(location="Andheri")
    jobLocationAvailable.objects.create(location="Vashi")
    jobLocationAvailable.objects.create(location="Pune")
    jobLocationAvailable.objects.create(location="Bengaluru")
    jobLocationAvailable.objects.create(location="Chennai")
    jobLocationAvailable.objects.create(location="Hyderabad")
    jobLocationAvailable.objects.create(location="Remote(WFH)")
    jobLocationAvailable.objects.create(location="Borivali")
    jobLocationAvailable.objects.create(location="Delhi")
    jobLocationAvailable.objects.create(location="Pimple Saudagar")

    qualificationAvailable.objects.create(qualificationName="Post Graduation")
    qualificationAvailable.objects.create(qualificationName="Graduation")
    qualificationAvailable.objects.create(qualificationName="Diploma")
    qualificationAvailable.objects.create(qualificationName="12th Board")
    qualificationAvailable.objects.create(qualificationName="10th Board")
    

    User.objects.create(
        password="admin",
        first_name="admin",
        last_name="admin",
        username="admin",
        email="admin",
        is_staff=False,
        is_active=True,
        is_superuser=True,
    )

    return HttpResponse("Data Added Successfully")


