# Generated by Django 4.2.5 on 2024-02-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobLocationAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('highestQualification', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=50)),
                ('yearOfPassing', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=10)),
                ('middleName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('mobileNumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('jobLocationSelected', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='workingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresher', models.BooleanField(default=True)),
                ('working', models.BooleanField(default=False)),
                ('companyName', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('lastDate', models.DateField()),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AddField(
            model_name='qualification',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.user'),
        ),
    ]
