# Generated by Django 4.2.5 on 2024-02-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0003_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='student',
        ),
    ]
