# Generated by Django 4.2.5 on 2024-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0004_rename_user_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobLocationAvailable',
        ),
        migrations.RemoveField(
            model_name='workingdetails',
            name='studentID',
        ),
        migrations.DeleteModel(
            name='qualification',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='workingDetails',
        ),
    ]
