# Generated by Django 4.2.5 on 2024-02-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=128)),
                ('courseTopicIds', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='subTopic',
            fields=[
                ('subTopicId', models.AutoField(primary_key=True, serialize=False)),
                ('subTopicName', models.CharField(max_length=128)),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('lectureId', models.AutoField(primary_key=True, serialize=False)),
                ('lectureName', models.CharField(max_length=128)),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='completedLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.lecture')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.student')),
                ('subTopicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.subtopic')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.topic')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courseId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portalApp.course'),
            preserve_default=False,
        ),
    ]
