# Generated by Django 4.2.5 on 2024-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0008_topic_topictype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topicType',
        ),
        migrations.AddField(
            model_name='topic',
            name='selfLearningTopic',
            field=models.BooleanField(default=True),
        ),
    ]
