# Generated by Django 4.2.5 on 2024-02-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0009_remove_topic_topictype_topic_selflearningtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='topicId',
        ),
        migrations.AddField(
            model_name='lecture',
            name='subTopicId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portalApp.subtopic'),
            preserve_default=False,
        ),
    ]
