# Generated by Django 4.2.5 on 2024-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0010_remove_lecture_topicid_lecture_subtopicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lectureName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='subTopicName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topicName',
            field=models.CharField(max_length=256),
        ),
    ]
