# Generated by Django 4.2.5 on 2024-02-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0011_alter_lecture_lecturename_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='completedLecture',
            new_name='classLectureCompleted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courseId',
        ),
        migrations.CreateModel(
            name='selfCompletedLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.lecture')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.student')),
                ('subTopicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.subtopic')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batchId', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=128)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='batchId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portalApp.batch'),
            preserve_default=False,
        ),
    ]
