# Generated by Django 4.2.5 on 2024-02-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0012_rename_completedlecture_classlecturecompleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlecturecompleted',
            name='studentId',
        ),
        migrations.AddField(
            model_name='classlecturecompleted',
            name='batchId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portalApp.batch'),
            preserve_default=False,
        ),
    ]
