# Generated by Django 4.2.5 on 2024-03-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portalApp', '0014_student_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('mobileNumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('jobLocationSelected', models.CharField(max_length=256)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalApp.batch')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
