# Generated by Django 4.2.5 on 2024-03-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0017_alter_extendeduser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='batchId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portalApp.batch'),
        ),
    ]
