# Generated by Django 4.2.5 on 2024-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0019_extendeduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='jobLocationSelected',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
