# Generated by Django 4.2.5 on 2024-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0020_alter_extendeduser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualificationAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblocationavailable',
            name='address',
        ),
    ]
