# Generated by Django 4.2.5 on 2024-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0021_qualificationavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='middleName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
