# Generated by Django 4.2.5 on 2024-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0023_alter_qualification_studentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
