# Generated by Django 4.2.5 on 2024-03-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalApp', '0026_alter_selfcompletedlecture_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
